"""init db

Revision ID: 1901d3247aa1
Revises: 
Create Date: 2021-06-30 20:22:09.895355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1901d3247aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_home', sa.String(length=128), nullable=False),
    sa.Column('team_away', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('score_team_home', sa.Integer(), nullable=True),
    sa.Column('score_team_away', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'bets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bets', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('bets')
    op.drop_table('matches')
    # ### end Alembic commands ###
